language: generic

sudo: required

before_install:
  - sudo echo 'deb http://archive.raspbian.org/raspbian/ jessie main'>>/etc/apt/sources.list

script:
  - "cat /etc/apt/sources.list"
  - "./buildraw"
