language: generic

sudo: required

before_script:
  - echo "deb http://archive.raspbian.org/raspbian/ jessie main" | sudo tee -a /etc/apt/sources.list

script:
  - "cat /etc/apt/sources.list"
  - "./buildraw"
