name: OnPush-Script

on: push

jobs:
    onpush-scripts:
        name: Push scripts
        runs-on: [self-hosted]
        steps:
            - name: Checkout push scripts
              uses: actions/checkout@v2
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  repository: jimyang2008/fireaction
                  ref: master
                  token: ${{ secrets.YJ_PAT }}
                  path: fireaction

            - name: Get current working directory
              run: pwd

            - name: Run bash scripts
              run: run-parts scripts/push/
              working-directory: fireaction

