name: OnPush-Script

on: push

jobs:
    script:
        name: Push scripts
        runs-on: [self-hosted]
        steps:
            - name: Checkout push scripts
              uses: actions/checkout@v2
              with:
                  repository: jimyang2008/fireaction
                  ref: master
                  path: fireaction

            - name: Get current working directory
              run: pwd

            - name: Run bash scripts
              run: run-parts scripts/push/

