name: OnPush-Script

on: push

jobs:
    onpush-scripts:
        name: Push scripts
        runs-on: ${{ matrix.platform }}
        strategy:
            matrix:
                platform: [ Red, Blue, Navy, Gold]
        steps:
            - name: Checkout push scripts
              uses: actions/checkout@v2

            - name: Checkout push scripts
              uses: actions/checkout@v2
              with:
                  repository: jimyang2008/fireaction
                  ref: main
                  token: ${{ secrets.ACCESS_TOKEN }}
                  path: fireaction

            - name: Get system info
              run: |
                  hostname
                  ip --br a
                  uname -a
                  scripts/sanity_check.sh

            - name: Run bash scripts
              run: run-parts scripts/push/
              working-directory: fireaction

