name: OnPush-Script

on: push

jobs:
    script:
        name: Push scripts
        runs-on: [self-hosted]
        steps:
            - name: Checkout push scripts
              run: git clone https://github.com/jimyang2008/fireaction
              working-direcotry: /home/pi

            - name: Get current working directory
              run: pwd

            - name: Run bash scripts
              run: run-parts scripts/push/
              working-direcotry: /home/pi/fireaction

