name: OnPR-Script

on: pull_request

jobs:
    onpr-scripts:
        name: PR scripts
        runs-on: ${{ matrix.platform }}
        strategy:
            matrix:
                platform: [ Red, Blue, Navy, Gold ]
        steps:
            - name: Checkout Firewalla
              uses: actions/checkout@v2

            - name: Sanity check
              run: scripts/sanity_check.sh

            - name: Run PR scripts
              run: run-parts /home/pi/firewaction/scripts/pr/

