name: OnPR-Script
on: pull_request

jobs:
    onpr-scripts:
        name: pull request scripts
        runs-on: ${{ matrix.platform }}
        env:
          WS_FIREWALLA: /home/pi/firewalla
          WS_FIREACTION: /home/pi/fireaction
          GITHUB_TOKEN: secrets.GITHUB_TOKEN 
        strategy:
            matrix:
                platform: [ Gold20 ]
        steps:
            - name: Link Firewalla
              run: pwd
              
            - name: Checkout Firewalla
              uses: actions/checkout@v2

            - name: Run PR scripts
              run: run-parts $WS_FIREACTION/scripts/pr/
